### ISSUE TITLE
Level gets stuck spamming WHs

### ISSUE THREAD

**Issue by heldplayer** [YeOldeWH/MonsterMinigameWormholeWarp#38]
After a few minutes of the script running, and while charging, the game will get stuck and not update the level, the monsters and abilities used. When the level gets beaten and the jump happens the script still thinks its charging. This causes a lot of people having their script spam WHs on random levels and slows us down. A refresh is enough to fix it temporarily.

**Comment by heldplayer** [comment]
A suggestion might be to do a refresh every 5 minutes with ~1 minute variance.

This refresh would happen regardless of whether we're charging or not.

**Comment by lolbifrons** [comment]
The script should auto-refresh anyway just to make sure that no one is more than x minutes out of date.

**Comment by Atombath** [comment]
was fixed in 6.1.2

**Comment by heldplayer** [comment]
It is indeed fixed
