### ISSUE TITLE
Please revert broken pushes when you are working on a fix.

### ISSUE THREAD

**Issue by lolbifrons** [YeOldeWH/MonsterMinigameWormholeWarp#44]
It doesn't make sense to leave a broken version up, no matter how soon the eta of the fix is.  We wasted a boss during the short time the script was broken.

**Comment by lolbifrons** [comment]
Script is still broken on 7.0.1.

**Comment by DannyDaemonic** [comment]
Sorry. We wanted to revert, but Skullcrown had taken away all of the devs' collaborator permissions due to some internal - or perhaps rather external - politics.
