### ISSUE TITLE
Settings panel doesn't actually change many settings.

### ISSUE THREAD

**Issue by lolbifrons** [YeOldeWH/MonsterMinigameWormholeWarp#48]
Crit text, All text, and Troll Tracking all behave like they have their default value no matter whether they are checked or exed on the settings page; clicking the settings button does nothing for these settings.

**Comment by lolbifrons** [comment]
I'm slightly mistaken, the behavior is more complicated than that, but it doesn't behave like it should.

**Comment by awstanley** [comment]
If you're still seeing this you're probably on the "new" UI which has been reverted.  You may need to force a refresh or re-install the script.

**Comment by lolbifrons** [comment]
Yeah this no longer applies with the reversion.  I'm closing it.
