### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ExorDG** [YeOldeWH/MonsterMinigameWormholeWarp#57]
Uncaught TypeError: Cannot read
property 'abilities' of undefined
 
CSceneGame.UpdateEnemies @ running.js?v=8907fsd&l=english:1147
CSceneGame.OnGameDataUpdate @ running.js?v=8907fsd&l=english:922
(anonymous function) @ running.js?v=8907fsd&l=english:335
(anonymous function) @ network.js?v=8907fsd&l=english:89
m.Callbacks.j @ jquery-1.11.1.min.js?v=.isFTSRckeNhC:2
m.Callbacks.k.fireWith @ jquery-1.11.1.min.js?v=.isFTSRckeNhC:2
x @ jquery-1.11.1.min.js?v=.isFTSRckeNhC:4
$.ajaxTransport.send.callback @ jquery-ajax-native.js?v=.tVg4PgQn0y2G:107

Getting this A LOT and no visual except showing level then fade down then show as the game moves from level to level.

**Comment by awstanley** [comment]
If it's only in running.js (and not in the VM) then it's probably not a side effect of the script, but rather Valve's backend.  Try loading the page with the script disabled to see if this is still happening.

**Comment by Exor18** [comment]
I am running it in incognito mode in chrome so that I can have my little brother's account help out with SMG same time my account in non-incognito mode. I am not sure if that's the cause? It was working fine for few hours then stopped working?

**Comment by awstanley** [comment]
My understanding is that incognito will cause issues, though I'm not sure if this is amongst them :)

A few other users have reported similar issues (game data not loading, etc.) in the last few hours, with and without the script across different browsers.

**Comment by DannyDaemonic** [comment]
This is, unfortunately, a rather common error we get with the Monster Minigame client. It does seem to happen at about the same frequency both with and without our script.
